In [1]:
from data_load import load, load_qualtrics_data, merge_sync_qa_data, convert_data_time_series

# load synchrony data
synchrony_df = load()

# load qualtrics data
qa_df = load_qualtrics_data()

# merge qa data with sync data
merged_df = merge_sync_qa_data(synchrony_df, qa_df)
merged_df.head()

# convert data to time series for plotting
time_df = convert_data_time_series(synchrony_df, merged_df)

time_df.head()

c:\Users\mashf\OneDrive\Desktop\Thesis_code\data_load.py:278: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time_df['cross_corr_ibi'] = time_df['cross_corr_ibi'].apply(lambda x: np.convolve(x, np.ones(window_length)/window_length, mode='valid'))
c:\Users\mashf\OneDrive\Desktop\Thesis_code\data_load.py:290: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.54736842 0.29473684 0.37894737 0.29473684 0.14736842 0.36842105
 0.25263158 0.21052632 0.04210526 0.12631579 0.04210526 0.73473684
 0.54736842 0.04210526 0.29473684 0.11578947 1.         0.25263158
 0.12631579 0.16842105 0.16842105 0.08421053 0.46947368 0.25263158
 0.16842105 0.08421053 0.08421053 0.02105263 0.28631579 0.16842105
 0.         0.08421053 0.08421053 0.02105263 0.12210526 0.16842105
 0.08421053 0.12631579 0.04210526 0.         0.30526316]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  time_df.loc[time_df['order'] == time_df['max_order'], 'game_score_normalized'] = synchrony_df['game_score_normalized']

,experiment,level,game_score,cross_corr_ibi,max_corr_ibi,Age,Gender,familiarity,Overall Collaboration,order,new_order,game_score_normalized,max_order,level_num,max_cross_corr_ibi_norm
0,Trial 01,asymmetric_advantages,280,0.009742,1.51965,"26, 26","Male, Male",1,4.5,0,0,0.0,1164,1,NaN
0,Trial 01,asymmetric_advantages,280,0.009443,1.51965,"26, 26","Male, Male",1,4.5,1,1,0.0,1164,1,NaN
0,Trial 01,asymmetric_advantages,280,0.0091,1.51965,"26, 26","Male, Male",1,4.5,2,2,0.0,1164,1,NaN
0,Trial 01,asymmetric_advantages,280,0.008723,1.51965,"26, 26","Male, Male",1,4.5,3,3,0.0,1164,1,NaN
0,Trial 01,asymmetric_advantages,280,0.008317,1.51965,"26, 26","Male, Male",1,4.5,4,4,0.0,1164,1,NaN

In [2]:
merged_df

,experiment,level,cross_corr_ibi,max_corr_ibi,game_score,familiarity,ibi_0,ibi_1,signal_0,signal_1,...,game_score_normalized,Age,Gender,Familiarity,Overall Collaboration,Your Collaboration,Partner Collaboration,Your Communication\r\n,Partner Communication,Performance Improvement\r\n
0,Trial 01,asymmetric_advantages,"[0.023990871243635078, 0.028307161547003083, 0...",1.519650,280,1,"[0.2533714087180087, 1.038259030669525, 1.8991...","[-7.87076479660795, -31.70462621718248, -51.35...","[426, 459, 493, 516, 524, 513, 513, 519, 535, ...","[497, 500, 504, 502, 499, 488, 488, 481, 478, ...",...,0.547368,"26, 26","Male, Male","Familiar, Familiar",4.5,5.0,4.5,4.0,4.5,4.0
1,Trial 01,coordination_ring,"[0.2833266527402388, 0.30794918778256264, 0.33...",0.411426,160,1,"[23.8985925686464, 42.474165801223215, 60.1178...","[-16.256404060197493, -17.8284768496341, -19.3...","[540.0, 528.0, 518.0, 513.0, 513.0, 517.0, 519...","[508.0, 510.0, 513.0, 520.0, 523.0, 527.0, 531...",...,0.294737,"26, 26","Male, Male","Familiar, Familiar",4.5,5.0,4.5,4.0,4.5,4.0
2,Trial 01,cramped_room,"[-0.06801178907534869, -0.059035837619558836, ...",0.565981,200,1,"[90.81573625558981, 109.76733658539175, 126.95...","[-27.369703685688425, -45.33724200188909, -62....","[501.0, 500.0, 499.0, 499.0, 498.0, 493.0, 492...","[502.0, 505.0, 506.0, 512.0, 515.0, 514.0, 517...",...,0.378947,"26, 26","Male, Male","Familiar, Familiar",4.5,5.0,4.5,4.0,4.5,4.0
3,Trial 01,forced_coordination,"[-0.1894187219264119, -0.18310182004102366, -0...",1.162827,160,1,"[11.02013578662807, 11.14330219873296, 11.2608...","[-0.9359571224624598, -12.403820199848216, -23...","[549, 542, 546, 529, 520, 525, 530, 536, 543, ...","[504, 503, 514, 500, 494, 490, 489, 489, 492, ...",...,0.294737,"26, 26","Male, Male","Familiar, Familiar",4.5,5.0,4.5,4.0,4.5,4.0
4,Trial 01,forced_coordination_tomato,"[-0.09526813585891905, -0.08532874889386913, -...",0.651763,90,1,"[-24.365594446440454, -25.30806320097629, -26....","[14.223764982524207, 9.366961629144368, 4.2968...","[584, 572, 554, 534, 518, 505, 490, 482, 474, ...","[519, 523, 521, 516, 509, 502, 499, 499, 499, ...",...,0.147368,"26, 26","Male, Male","Familiar, Familiar",4.5,5.0,4.5,4.0,4.5,4.0
5,Trial 01,marshmallow_experiment,"[-0.08633664069499175, -0.09371487412507849, -...",0.642869,195,1,"[-42.79570049965794, -36.11069730781816, -29.6...","[16.097492776197786, 16.594386084934097, 17.16...","[0, 78, 104, 148, 201, 251, 298, 329, 356, 384...","[0, 462, 504, 526, 546, 587, 634, 672, 693, 68...",...,0.368421,"26, 26","Male, Male","Familiar, Familiar",4.5,5.0,4.5,4.0,4.5,4.0
6,Trial 02,asymmetric_advantages,"[-0.07703980026607654, -0.07857095357515717, -...",0.963500,140,1,"[-3.2322255137014015, -3.086917083788977, -2.8...","[-37.46191105895734, 46.29883475044633, 129.31...","[484.0, 483.0, 485.0, 487.0, 489.0, 492.0, 496...","[499.0, 499.0, 500.0, 511.0, 534.0, 565.0, 595...",...,0.252632,"23, 27","Female, Male","Familiar, Familiar",4.0,3.5,4.5,3.5,3.5,4.5
7,Trial 02,coordination_ring,"[0.12608147430292593, 0.13270947598600555, 0.1...",1.469491,120,1,"[-11.438686852510653, -13.93142741507116, -17....","[-0.8502953589560641, -11.545437417574101, -22...","[505.0, 510.0, 516.0, 519.0, 521.0, 520.0, 516...","[487.0, 486.0, 488.0, 492.0, 493.0, 496.0, 499...",...,0.210526,"23, 27","Female, Male","Familiar, Familiar",4.0,3.5,4.5,3.5,3.5,4.5
8,Trial 02,cramped_room,"[-0.07374416687712233, -0.07422860528181666, -...",0.357121,40,1,"[-25.444656237271257, -26.257992340569217, -27...","[-0.3905771394712756, -0.28024593124817304, -0...","[492.0, 494.0, 495.0, 497.0, 497.0, 497.0, 498...","[536.0, 532.0, 525.0, 518.0, 509.0, 502.0, 499...",...,0.042105,"23, 27","Female, Male","Familiar, Familiar",4.0,3.5,4.5,3.5,3.5,4.5
9,Trial 02,forced_coordination,"[-0.08920686344002302, -0.08752755710756921, -...",1.012805,80,1,"[-30.27165261906391, -30.960623772954207, -31....","[63.54939020517083, 77.66068703476192, 91.3150...","[553, 551, 542, 529, 514, 501, 490, 481, 472, ...","[480, 487, 496, 517, 558, 607, 655, 688, 692, ...",...,0.126316,"23, 27","Female, Male","Familiar, Familiar",4.0,3.5,4.5,3.5,3.5,4.5
10,Trial 02,forced_coordination_tomato,"[0.4302767223764579, 0.45125140650986345, 0.46...",0.651087,40,1,"[5.665589079473203, -5.5673365382015785, -16.2...","[1.4992392485928245, -1.8415167430737525, -5.2...","[492, 490, 489, 490, 491, 495, 495, 497, 496, ...","[408.0, 415.0, 431.0, 448.0, 470.0, 484.0, 493...",...,0.042105,"23, 27","Female, Male","Familiar, Familiar",4.0,3.5,4.5,3.5,3.5,4.5
11,Trial 02,marshmallow_experiment,"[0.18038354711052848, 0.17682513674793288, 0.1...",1.055200,369,1,"[-32.096646013943385, -56.89417157336485, -81....","[17.24163795698516, -4.718578494417347, -26.66...","[501, 499, 498, 501, 508, 517, 532, 539, 538, ...","[494, 481, 475, 477, 486, 496, 519, 546, 559, ...",...,0.734737,"23, 27","Female, Male","Familiar, Familiar",4.0,3.5,4.5,3.5,3.5,4.5
12,Trial 03,asymmetric_advantages,"[0.06452700388388717, 0.07687288229459421, 0.0...",0.483296,280,0,"[8.742329375885767, 18.720403531452984, 27.681...","[-16.61014892246628, -13.28359813268881, -10.0...","[509, 500, 507, 507, 508, 508, 503, 504, 514, ...","[511, 513, 514, 517, 520, 524, 526, 526, 524, ...",...,0.547368,"27, 23","Male, Female","Unfamiliar, Unfamiliar",3.0,4.0,4.0,3.5,3.0,3.5
13,Trial 03,cramped_room,"[-0.31299353700991944, -0.31358250750685535, -...",0.775515,40,0,"[-0.5935367776601312, 0.24212216160374256, 1.0...","[0.34401671654399246, -1.0467668372694992, -2....","[470.0, 471.0, 473.0, 477.0, 486.0, 495.0, 506...","[511.0, 511.0, 511.0, 513.0, 515.0, 520.0, 527...",...,0.042105,"27, 23","Male, Female","Unfamiliar, Unfamiliar",3.0,4.0,4.0,3.5,3.0,3.5
14,Trial 03,forced_coordination,"[-0.24643460192618277, -0.2399883925300032, -0...",0.959233,160,0,"[-6.76574879033568, -6.725431675874297, -6.294...","[36.08309777067534, 24.733002733948076, 13.605...","[531, 541, 542, 540, 531, 524, 514, 508, 503, ...","[526, 529, 530, 529, 526, 521, 518, 518, 515, ...",...,0.294737,"27, 23","Male, Female","Unfamiliar, Unfamiliar",3.0,4.0,4.0,3.5,3.0,3.5
15,Trial 03,forced_coordination_tomato,"[-0.2341929177519907, -0.24366175996020023, -0...",0.844187,75,0,"[-8.284031637778881, -11.000581247155415, -13....","[-18.39760205850641, -24.378553378062488, -30....","[529, 521, 511, 503, 501, 508, 509, 506, 505, ...","[514.0, 516.0, 515.0, 514.0, 514.0, 513.0, 513...",...,0.115789,"27, 23","Male, Female","Unfamiliar, Unfamiliar",3.0,4.0,4.0,3.5,3.0,3.5
16,Trial 03,marshmallow_experiment,"[-0.14513886388873143, -0.15048702820480914, -...",0.281052,495,0,"[-28.65412999840967, -48.18134218125773, -67.5...","[20.937123563304453, 20.78115305831536, 20.694...","[507, 510, 515, 520, 520, 519, 519, 517, 514, ...","[510, 511, 512, 511, 510, 512, 511, 511, 511, ...",...,1.000000,"27, 23","Male, Female","Unfamiliar, Unfamiliar",3.0,4.0,4.0,3.5,3.0,3.5
17,Trial 04,asymmetric_advantages,"[-0.032045374579569214, -0.03897221797860535, ...",0.925072,140,0,"[-44.36227490959464, -72.41174274107304, -99.4...","[-2.151795948943872, 46.90199417302473, 94.097...","[507, 508, 507, 507, 508, 506, 504, 503, 504, ...","[515, 519, 522, 524, 525, 525, 522, 519, 518, ...",...,0.252632,"27, 23","Female, Female","Unfamiliar, Unfamiliar",4.5,4.5,4.5,3.5,3.0,3.5
18,Trial 04,coordination_ring,"[-0.14495943751627494, -0.13866865304725054, -...",1.111542,80,0,"[-20.517927647328065, -19.68255396342391, -18....","[5.22898073303424e-07, 4.861398379557773e-07, ...","[495, 497, 498, 502, 505, 507, 508, 505, 503, ...","[514, 515, 515, 516, 515, 515, 514, 514, 513, ...",...,0.126316,"27, 23","Female, Female","Unfamiliar, Unfamiliar",4.5,4.5,4.5,3.5,3.0,3.5
19,Trial 04,cramped_room,"[0.08278907976875303, 0.08346953450781966, 0.0...",0.717233,100,0,"[3.233682387873678, 2.2230806406372468, 1.1353...","[13.223670092114899, 18.431500952896894, 23.41...","[498, 497, 495, 493, 490, 489, 489, 488, 487, ...","[513.0, 512.0, 513.0, 511.0, 510.0, 507.0, 505...",...,0.168421,"27, 23","Female, Female","Unfamiliar, Unfamiliar",4.5,4.5,4.5,3.5,3.0,3.5
20,Trial 04,forced_coordination,"[0.053722943862349465, 0.04512622251585108, 0....",0.956268,100,0,"[16.65991453923998, -22.359167982355046, -59.8...","[5.22898073303424e-07, 4.861398379557773e-07, ...","[507, 507, 506, 505, 504, 504, 504, 504, 505, ...","[515.0, 515.0, 515.0, 517.0, 518.0, 518.0, 519...",...,0.168421,"27, 23","Female, Female","Unfamiliar, Unfamiliar",4.5,4.5,4.5,3.5,3.0,3.5
21,Trial 04,forced_coordination_tomato,"[0.03539168407874038, 0.038327825642592045, 0....",1.694039,60,0,"[11.083461683424218, 10.258517400051579, 9.545...","[5.22898073303424e-07, 4.861398379557773e-07, ...","[500.0, 497.0, 494.0, 495.0, 495.0, 492.0, 491...","[515.0, 516.0, 516.0, 516.0, 517.0, 516.0, 515...",...,0.084211,"27, 23","Female, Female","Unfamiliar, Unfamiliar",4.5,4.5,4.5,3.5,3.0,3.5
22,Trial 04,marshmallow_experiment,"[-0.2678296585148963, -0.26988693049912654, -0...",1.873071,243,0,"[-75.06639622839447, -78.02826010027424, -81.0...","[5.22898073303424e-07, 4.861398379557773e-07, ...","[485, 483, 485, 490, 496, 507, 515, 521, 522, ...","[512.0, 514.0, 516.0, 519.0, 521.0, 524.0, 524...",...,0.469474,"27, 23","Female, Female","Unfamiliar, Unfamiliar",4.5,4.5,4.5,3.5,3.0,3.5
23,Trial 05,asymmetric_advantages,"[0.0643628225405775, 0.07096583960163563, 0.07...",0.987733,140,0,"[5.691256842589135, 19.02302527278532, 31.8904...","[6.741335540093623, 7.133422016657864, 7.52215...","[507, 519, 531, 542, 546, 541, 532, 523, 514, ...","[807, 712, 605, 518, 445, 397, 366, 364, 388, ...",...,0.252632,"27, 26","Male, Female","Unfamiliar, Unfamiliar",3.5,3.5,4.0,3.5,4.5,4.0
24,Trial 05,coordination_ring,"[0.022202979195031333, 0.017163779336424847, 0...",0.498371,100,0,"[-5.8144225033873544, -6.193978411474484, -6.6...","[-7.349981427165553, -7.5958958335608395, -7.8...","[502, 499, 497, 496, 497, 499, 499, 500, 499, ...","[798.0, 792.0, 744.0, 671.0, 590.0, 528.0, 469...",...,0.168421,"27, 26","Male, Female","Unfamiliar, Unfamiliar",3.5,3.5,4.0,3.5,4.5,4.0
25,Trial 05,cramped_room,"[0.019211210741818124, 0.025242719391432366, 0...",0.432026,60,0,"[7.614187949415884, 7.790309914077415, 7.92817...","[-0.4320624657975031, -0.28028426214161273, -0...","[498.0, 498.0, 498.0, 499.0, 500.0, 499.0, 500...","[392.0, 422.0, 464.0, 507.0, 540.0, 556.0, 555...",...,0.084211,"27, 26","Male, Female","Unfamiliar, Unfamiliar",3.5,3.5,4.0,3.5,4.5,4.0
26,Trial 05,forced_coordination,"[-0.21912698127749386, -0.2236140751693059, -0...",0.460313,60,0,"[-6.163632939973132, -6.9900182227100185, -7.8...","[3.712632820441756, 2.38829150219706, 1.079608...","[502, 501, 501, 502, 506, 515, 524, 536, 542, ...","[508, 480, 460, 451, 448, 446, 433, 448, 465, ...",...,0.084211,"27, 26","Male, Female","Unfamiliar, Unfamiliar",3.5,3.5,4.0,3.5,4.5,4.0
27,Trial 05,forced_coordination_tomato,"[-0.28224095929454285, -0.2841532563690575, -0...",0.577684,30,0,"[20.15126963876608, 21.812555480776968, 23.468...","[0.4235557555261667, 0.9901518237540005, 1.536...","[515, 524, 531, 533, 531, 527, 519, 513, 509, ...","[728, 689, 623, 561, 503, 462, 432, 414, 419, ...",...,0.021053,"27, 26","Male, Female","Unfamiliar, Unfamiliar",3.5,3.5,4.0,3.5,4.5,4.0
28,Trial 05,marshmallow_experiment,"[-0.12652349043394887, -0.13138032407263886, -...",0.641424,156,0,"[-6.604784999559276, -10.554011058000924, -14....","[6.781849965197412, 12.119822124796567, 17.297...","[504, 504, 505, 504, 503, 502, 503, 507, 512, ...","[489.0, 540.0, 626.0, 717.0, 785.0, 799.0, 765...",...,0.286316,"27, 26","Male, Female","Unfamiliar, Unfamiliar",3.5,3.5,4.0,3.5,4.5,4.0
29,Trial 06,asymmetric_advantages,"[0.007940201497367632, 0.00721924271205785, 0....",0.829275,100,0,"[-0.8488766122524621, -1.0058207470957896, -1....","[5.22898073303424e-07, 4.861398379557773e-07, ...","[993, 994, 993, 834, 562, 340, 165, 88, 109, 2...","[516, 515, 515, 515, 517, 515, 515, 515, 514, ...",...,0.168421,"27, 28","Female, Male","Unfamiliar, Unfamiliar",4.0,4.0,3.5,3.0,3.0,4.0
30,Trial 06,coordination_ring,"[0.015047594622894261, 0.013142395793485095, 0...",0.662644,20,0,"[2.9999007720422695, 0.10571865139432346, -2.7...","[5.22898073303424e-07, 4.861398379557773e-07, ...","[164, 300, 470, 667, 903, 993, 993, 993, 994, ...","[516, 515, 514, 513, 514, 514, 515, 515, 514, ...",...,0.000000,"27, 28","Female, Male","Unfamiliar, Unfamiliar",4.0,4.0,3.5,3.0,3.0,4.0
31,Trial 06,cramped_room,"[0.20918437731093617, 0.22902002277245925, 0.2...",0.254757,60,0,"[-1.2998367332759935, 2.049316925097024, 5.351...","[1.8335843802644283e-05, 1.9213249684261968e-0...","[277.0, 291.0, 305.0, 323.0, 366.0, 452.0, 652...","[514.0, 514.0, 515.0, 513.0, 514.0, 514.0, 514...",...,0.084211,"27, 28","Female, Male","Unfamiliar, Unfamiliar",4.0,4.0,3.5,3.0,3.0,4.0
32,Trial 06,forced_coordination,"[-0.07535878941003141, -0.1013997154820308, -0...",0.389353,60,0,"[-6.803901032201804, -29.976973320637097, -52....","[5.22898073303424e-07, 4.861398379557773e-07, ...","[449, 576, 806, 993, 993, 993, 993, 993, 893, ...","[514, 512, 513, 514, 513, 515, 515, 514, 514, ...",...,0.084211,"27, 28","Female, Male","Unfamiliar, Unfamiliar",4.0,4.0,3.5,3.0,3.0,4.0
33,Trial 06,forced_coordination_tomato,"[-0.2791262957200048, -0.2835193140388128, -0....",0.507405,30,0,"[-3.8366143291168107, -3.985543547858591, -4.1...","[5.22898073303424e-07, 4.861398379557773e-07, ...","[993, 783, 523, 273, 107, 32, 65, 152, 289, 42...","[517, 517, 518, 517, 517, 516, 517, 517, 517, ...",...,0.021053,"27, 28","Female, Male","Unfamiliar, Unfamiliar",4.0,4.0,3.5,3.0,3.0,4.0
34,Trial 06,marshmallow_experiment,"[-0.1025598892733687, -0.08837354604682911, -0...",0.201623,78,0,"[-6.260345464996405, -6.491433048016027, -6.77...","[-1.652695460975794e-05, -1.5299584311223603e-...","[619.0, 624.0, 594.0, 539.0, 480.0, 433.0, 393...","[516.0, 516.0, 515.0, 514.0, 514.0, 514.0, 513...",...,0.122105,"27, 28","Female, Male","Unfamiliar, Unfamiliar",4.0,4.0,3.5,3.0,3.0,4.0
35,Trial 07,asymmetric_advantages,"[-0.17536164285135591, -0.16435196220050102, -...",0.611270,100,1,"[-1.5299164095054147, -1.635939986284403, -1.7...","[15.328969336707765, 18.13055232263572, 19.576...","[516, 458, 421, 408, 411, 432, 463, 493, 523, ...","[556, 575, 614, 664, 710, 732, 726, 686, 634, ...",...,0.168421,"23, 23","Female, Male","Familiar, Familiar",3.5,3.5,3.5,4.5,4.0,3.5
36,Trial 07,coordination_ring,"[-0.09579706204288958, -0.10791932828791564, -...",0.734152,60,1,"[-0.14385738978964396, 2.9406916154115077, 5.9...","[12.994717600578086, 14.82463034171107, 16.681...","[505, 503, 500, 500, 510, 532, 561, 586, 590, ...","[515.0, 517.0, 512.0, 506.0, 506.0, 507.0, 502...",...,0.084211,"23, 23","Female, Male","Familiar, Familiar",3.5,3.5,3.5,4.5,4.0,3.5
37,Trial 07,cramped_room,"[0.13328231714321456, 0.1264101548725125, 0.12...",0.950180,80,1,"[3.741609036299772, -4.129453173940174, -11.71...","[59.537169381519014, 58.80774805453757, 58.154...","[490.0, 515.0, 567.0, 619.0, 685.0, 715.0, 703...","[485.0, 479.0, 476.0, 460.0, 467.0, 482.0, 494...",...,0.126316,"23, 23","Female, Male","Familiar, Familiar",3.5,3.5,3.5,4.5,4.0,3.5
38,Trial 07,forced_coordination,"[0.028156919134911522, 0.03536439980820576, 0....",0.492084,40,1,"[6.843668218598981, 7.955330733830928, 8.79441...","[39.05020771720821, 21.231385318038125, 4.2561...","[508, 502, 496, 494, 492, 492, 492, 494, 497, ...","[503, 500, 494, 487, 487, 487, 489, 492, 496, ...",...,0.042105,"23, 23","Female, Male","Familiar, Familiar",3.5,3.5,3.5,4.5,4.0,3.5
39,Trial 07,forced_coordination_tomato,"[-0.04305464759805081, -0.049575527456242524, ...",0.842071,20,1,"[-23.51257475942559, -25.784193663460382, -28....","[0.17027266548332873, 43.33773586506197, 86.89...","[470, 469, 470, 471, 474, 477, 479, 482, 485, ...","[545.0, 536.0, 527.0, 524.0, 524.0, 531.0, 555...",...,0.000000,"23, 23","Female, Male","Familiar, Familiar",3.5,3.5,3.5,4.5,4.0,3.5
40,Trial 07,marshmallow_experiment,"[0.12295944515698277, 0.1280921304992104, 0.13...",0.292670,165,1,"[-1.1891646176455737, -1.2558191066345596, -1....","[4.10019056904458, -3.0493070109156353, -9.432...","[482, 498, 514, 525, 527, 521, 510, 501, 494, ...","[512, 510, 511, 511, 511, 511, 509, 506, 505, ...",...,0.305263,"23, 23","Female, Male","Familiar, Familiar",3.5,3.5,3.5,4.5,4.0,3.5